### ISSUE TITLE
PSAR InvalidOptionError

### ISSUE THREAD

**Issue by freakinhippie** [cirla/tulipy#18]
When attempting to use the Parabolic Stop and Reversal I'm getting the following error:

```
>>> import tulipy as ti
>>> import numpy as np
>>> ti.TI_VERSION
'0.8.1'
>>> ti.psar(np.arange(5., 105.), np.arange(100.), 0.02, 0.02)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jcolson/anaconda3/lib/python3.6/site-packages/tulipy/__init__.py", line 919, in psar
    return lib.psar([high, low], [acceleration_factor_step, acceleration_factor_maximum])
  File "tulipy/lib/__init__.pyx", line 118, in tulipy.lib._Indicator.__call__ (tulipy/lib/__init__.c:3049)
tulipy.lib.InvalidOptionError
>>> from tulipy import lib
>>> lib.psar([np.arange(5., 105.), np.arange(100.)], [0.02, 0.02])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tulipy/lib/__init__.pyx", line 118, in tulipy.lib._Indicator.__call__ (tulipy/lib/__init__.c:3049)
tulipy.lib.InvalidOptionError
>>> 
```

Any thoughts as to what the cause might be?

**Comment by freakinhippie** [comment]
It seems this is caused by the **acceleration_factor_step** and **acceleration_factor_maximum** being set to the same value. I changed the maximum to a value greater than the step and that resolved it.

Thanks.

**Comment by cirla** [comment]
Sorry for the late reply, I was losing notifications for this repo to overly aggressive email filtering. I'm glad you got things working!
