### ISSUE TITLE
PSAR fires InvalidOptionError when it should raise InvalidInputError

### ISSUE THREAD

**Issue by neurotronix** [cirla/tulipy#38]
Consider following snippet, where I pass arrays of length 1 to `ti.psar()`:
``` python
>>> import tulipy as ti
>>> import numpy as np
>>> ti.psar(np.array([3]), np.array([1]),0.2,2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/stephan/.local/share/virtualenvs/renko-trader-w4B4BzK4/lib/python3.7/site-packages/tulipy/__init__.py", line 919, in psar
    return lib.psar([high, low], [acceleration_factor_step, acceleration_factor_maximum])
  File "tulipy/lib/__init__.pyx", line 105, in tulipy.lib._Indicator.__call__
tulipy.lib.InvalidOptionError
```

To me the error type is confusing, since clearly the inputs do not conform here. Wouldn't it make sense to raise `InvalidInputError` here?

**Comment by twoletters** [comment]
Any news on this? As soon as I need to specify an option, I get the error. I tried on adx and aroon with the same result. I'm willing to help with this but I need some guidance as I don't know where to start and what needs to be done.
