### ISSUE TITLE
unable to install tulipy

### ISSUE THREAD

**Issue by scubieman** [cirla/tulipy#43]
Running windows pycharm. Running numpy 1.19.3
Running python 3.8, tested with 3.9 same results. I keep getting error about numpy, but i am installing tulipy.

I tried install via command prompt also use "pip install tulipy" but that fails also.

`Collecting tulipy
  Using cached tulipy-0.4.0.tar.gz (110 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

DEPRECATION: The -b/--build/--build-dir/--build-directory option is deprecated. pip 20.3 will remove support for this functionality. A possible replacement is use the TMPDIR/TEMP/TMP environment variable, possibly combined with --no-clean. You can find discussion regarding this at https://github.com/pypa/pip/issues/8333.
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\ScubaTest\Desktop\python\test\Scripts\python.exe' 'C:\Users\ScubaTest\Desktop\python\test\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\SCUBAT~1\AppData\Local\Temp\tmp7o8pkrqe'
       cwd: C:\Users\ScubaTest\AppData\Local\Temp\pycharm-packaging\tulipy
  Complete output (20 lines):
  Traceback (most recent call last):
    File "C:\Users\ScubaTest\Desktop\python\test\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "C:\Users\ScubaTest\Desktop\python\test\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\ScubaTest\Desktop\python\test\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\ScubaTest\AppData\Local\Temp\pip-build-env-1egk7hbk\overlay\Lib\site-packages\setuptools\build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\ScubaTest\AppData\Local\Temp\pip-build-env-1egk7hbk\overlay\Lib\site-packages\setuptools\build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "C:\Users\ScubaTest\AppData\Local\Temp\pip-build-env-1egk7hbk\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 4, in <module>
      import numpy as np
    File "C:\Users\ScubaTest\AppData\Local\Temp\pip-build-env-1egk7hbk\overlay\Lib\site-packages\numpy\__init__.py", line 305, in <module>
      _win_os_check()
    File "C:\Users\ScubaTest\AppData\Local\Temp\pip-build-env-1egk7hbk\overlay\Lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
      raise RuntimeError(msg.format(__file__)) from None
  RuntimeError: The current Numpy installation ('C:\\Users\\ScubaTest\\AppData\\Local\\Temp\\pip-build-env-1egk7hbk\\overlay\\Lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\ScubaTest\Desktop\python\test\Scripts\python.exe' 'C:\Users\ScubaTest\Desktop\python\test\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\SCUBAT~1\AppData\Local\Temp\tmp7o8pkrqe' Check the logs for full command output.
`

**Comment by blueprintsud** [comment]
i have the same issue here

**Comment by GitHub-Valie** [comment]
Same issue on Python 3.8.3 (vscode is my IDE)
